config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
    # sessions: 'registrations/sessions'
  }

  resources :users, only: %i[index]
  # do
  #   resources :favorites, only: [:create, :destroy]
  # end

  # resources :products
  resources :products do
    # resources :favorites, only: [:create, :destroy]
    post 'favorite', on: :member, to: 'favorites#create', as: 'favorite'
    delete 'favorite', on: :member, to: 'favorites#destroy'
  end

  # resources :favorites, only: [:index]

  resources :categories

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.

  # Defines the root path route ("/")
  root "home#index"
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to category_path(@category), notice: 'Category created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category), notice: 'Category updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy

    redirect_to categories_path, notice: 'Category deleted'
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.slim
h1 Edit Category

= form_with(model: @category) do |form|
  - if @category.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@category.errors.count, "error")} error editing this category:"
      ul
        - @category.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.submit

app/views/categories/index.html.slim
h1 Categories list
br
#categories
  ul
    - @categories.each do |category|
      li
        =category.name
      

= link_to "New Category", new_category_path

app/views/categories/new.html.slim
h1 New Category

= form_with(model: @category) do |form|
  - if @category.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@category.errors.count, "error")} error creating this category:"
      ul
        - @category.errors.each do |error|
          li = error.full_message

  div
    = form.label :name, style: "display: block"
    = form.text_field :name

  div
    = form.submit

app/views/categories/show.html.slim
h1 Show this category
br
div id="#{dom_id @category}"
  p
    strong Id:
    =< @category.id
  p
    strong Name:
    =< @category.name

div
  = link_to "edit this category", edit_category_path(@category)
div
  = link_to "Delete this category", category_path(@category), data: { turbo_method: :delete }
div
  = link_to  "back to categories", categories_path 