config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
    # sessions: 'registrations/sessions'
  }

  resources :users, only: %i[index]
  # do
  #   resources :favorites, only: [:create, :destroy]
  # end

  # resources :products
  resources :products do
    # resources :favorites, only: [:create, :destroy]
    post 'favorite', on: :member, to: 'favorites#create', as: 'favorite'
    delete 'favorite', on: :member, to: 'favorites#destroy'
  end

  # resources :favorites, only: [:index]

  resources :categories

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.

  # Defines the root path route ("/")
  root "home#index"
end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :bigint           not null, primary key
#  description :text
#  price       :float
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_products_on_category_id  (category_id)
#  index_products_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#
class Product < ApplicationRecord
  include Favoritable

  belongs_to :category
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many_attached :images

  def favorite?(user)
    favorites.exists?(user: user)
  end

end

app/controllers/products_controller.rb
# frozen_string_literal: true
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit update destroy]
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @current_user = current_user
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to product_path(@product), notice: 'Product created.'

    else
      render :new, status: :unprocessable_entity

    end
  end

  def edit; end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product), notice: 'Product updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy

    redirect_to products_path, notice: 'Product was successfully destroyed.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :category_id, :user_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_favorite.html.slim
div#favorite
  - if current_user
    - if @product.favorite?(current_user)
      = link_to "Quitar de favoritos", favorite_product_path(@product), method: :delete, data: { turbo_stream: "replace", target: "favorite" }
    - else
      = link_to "Agregar a favoritos", favorite_product_path(@product), method: :post, data: { turbo_stream: "replace", target: "favorite" }
  - else
    = link_to "Sing in", new_user_session_path

app/views/products/_form.html.slim
= form_with(model: @product) do |form|
  - if @product.errors.any?
    div style="color: red"
      h2 = "#{pluralize(@product.errors.count, "error")} error handling this product"
      ul
        - @product.errors.each do |error|
          li = error.full_message

  div
    = form.label :title, style: "display: block"
    = form.text_field :title

  div
    = form.label :description, style: "display: block"
    = form.text_field :description

  div
    = form.label :price, style: "display: block"
    = form.number_field :price
  div
    = form.label :category_id, style: "display: block"
    = form.select :category_id, options_for_select(Category.all.collect { | category | [category.name, category.id] }), {}, {}
  div 
    = form.label :images, style: "display: block"
    = form.file_field :images, multiple: true

  div
    = form.submit

app/views/products/_product.html.slim
div id="#{dom_id product}"
  p
    strong Title:
    =< product.title
  p
    strong Description:
    =< product.description
  p
    strong Category Id:
    =< product.category_id
  p
    strong User Id:
    =< product.user_id
  p
    strong Price:
    =< product.price
  div
    strong Images:
    - product.images.each do |image|
      = image_tag(image, :width => 200)

app/views/products/edit.html.slim
h1 Edit this product
== render "form"

div
  = link_to  "back to products", products_path 

app/views/products/index.html.slim
h1 Products list

#products
  - @products.each do |product|
    p
      | Title: 
      = product.title
    p
      | Price: 
      = product.price
    div
      = image_tag(product.images.first, :width => 200) if product.images.attached?

    p
      = link_to "Show this product", product
    br


= link_to "New Product", new_product_path

app/views/products/my_products.html.slim
h1 My products

h1 Products list

#products
  - @products.each do |product|
    == render product
    p
      = link_to "Show this product", product
    br


= link_to "New Product", new_product_path

app/views/products/new.html.slim
h1 New product

== render "form"

br

div
  = link_to "Back to products", products_path

app/views/products/show.html.slim
h1 Show this product
== render "product", product: @product, current_user: current_user
div
  = link_to "edit this product", edit_product_path(@product)
div
  = link_to "Delete this product", product_path(@product), data: { turbo_method: :delete }
div
  = link_to "Back to products", products_path
div
  == render partial: 'favorite', locals: { product: @product, current_user: current_user }