config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
    # sessions: 'registrations/sessions'
  }

  resources :users, only: %i[index]
  # do
  #   resources :favorites, only: [:create, :destroy]
  # end

  # resources :products
  resources :products do
    # resources :favorites, only: [:create, :destroy]
    post 'favorite', on: :member, to: 'favorites#create', as: 'favorite'
    delete 'favorite', on: :member, to: 'favorites#destroy'
  end

  # resources :favorites, only: [:index]

  resources :categories

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>S1116FtRuby</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%# <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %> %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | S1116FtRuby
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    p.notice
      = notice
    p.alert
      = alert
    div.hola.my-4
      = link_to "products", products_path, class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mx-2 rounded"
      = link_to "categories", categories_path, class: "bg-orange-500 hover:bg-orange-700 text-white font-bold py-2 px-4 mx-2 rounded"

      - if current_user 
        = link_to "profile", users_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 mx-2 rounded"
        = link_to "my products", products_my_products_path, class: "bg-cyan-500 hover:bg-cyan-700 text-white font-bold py-2 px-4 mx-2 rounded"
        = link_to "logout", destroy_user_session_path, data: { turbo_method: :delete }, class: "bg-yellow-500 hover:bg-green-700 text-white font-bold py-2 px-4 mx-2 rounded"
      - else
        = link_to "login", new_user_session_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 mx-2 rounded"
      
    = yield